version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  application-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/payday_trade
    depends_on:
      - user-db
      - eureka-server

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: payday_trade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product
    depends_on:
      - product-db
      - eureka-server

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
